# frozen_string_literal: true

require_relative 'dojo/version'
require_relative 'dojo/kyu_8/double_char'
require_relative 'dojo/kyu_8/dna_to_rna'
require_relative 'dojo/kyu_8/short_long_short'
require_relative 'dojo/kyu_8/exclusive_or'
require_relative 'dojo/kyu_8/parse_nice_int'
require_relative 'dojo/kyu_8/player_health'
require_relative 'dojo/kyu_8/traffic_lights'
require_relative 'dojo/kyu_8/hello_world'
require_relative 'dojo/kyu_8/hoola_hoop'
require_relative 'dojo/kyu_8/get_character'
require_relative 'dojo/kyu_8/nearest_pump'
require_relative 'dojo/kyu_8/check_even'
require_relative 'dojo/kyu_8/dragon_slayer'
require_relative 'dojo/kyu_8/get_negative'
require_relative 'dojo/kyu_8/point_of_symmetry'
require_relative 'dojo/kyu_8/collinearity'
require_relative 'dojo/kyu_8/quadrants'
require_relative 'dojo/kyu_8/gravity_flip'
require_relative 'dojo/kyu_8/check_same_case'
require_relative 'dojo/kyu_8/quadratic_coefficients_solver'
require_relative 'dojo/kyu_8/quarter_of_the_year'
require_relative 'dojo/kyu_8/dynamic_method_calls'
require_relative 'dojo/kyu_8/closest_elevator'
require_relative 'dojo/kyu_8/total_amount_of_points'
require_relative 'dojo/kyu_8/sum_of_differences'
require_relative 'dojo/kyu_8/twice_as_old'
require_relative 'dojo/kyu_8/draw_stairs'
require_relative 'dojo/kyu_8/pillars'
require_relative 'dojo/kyu_8/count_the_sheep'
require_relative 'dojo/kyu_8/expression_matters'
require_relative 'dojo/kyu_8/students_grade'
require_relative 'dojo/kyu_8/area_or_perimeter'
require_relative 'dojo/kyu_8/the_feast_of_many_beasts'
require_relative 'dojo/kyu_8/find_nearest_square'
require_relative 'dojo/kyu_8/cat_years_dog_years'
require_relative 'dojo/kyu_8/century_of_the_year'
require_relative 'dojo/kyu_8/define_card_suit'
require_relative 'dojo/kyu_8/multiple_of_index'
require_relative 'dojo/kyu_8/csv_representation_of_array'
require_relative 'dojo/kyu_8/multiplication_table'
require_relative 'dojo/kyu_8/array_plus_array'
require_relative 'dojo/kyu_8/the_falling_speed_of_petals'
require_relative 'dojo/kyu_8/reverse_sequence'
require_relative 'dojo/kyu_8/convert_to_binary'
require_relative 'dojo/kyu_8/return_the_day'
require_relative 'dojo/kyu_8/string_contamination'
require_relative 'dojo/kyu_8/find_integral'
require_relative 'dojo/kyu_8/count_odd'

module Dojo
  class Error < StandardError; end
  # Your code goes here...
end
